name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug APK
      run: ./gradlew clean assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-artifact
        path: ./app/build/outputs/apk/debug/app-debug.apk
        
    - name: Slack - Send Msg
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,workflow,message,commit,author,eventName,took
        author_name: Heeg
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
      
    - name: Slack - Upload APK 
      uses: MeilCli/slack-upload-file@v1.0.0 
      with: 
        slack_token: ${{ secrets.SLACK_TOKEN }} 
        channels: '다잡아'
        initial_comment: 'APK File Upload' 
        file_type: 'apk' 
        file_name: 'app-debug.apk'
        file_path: './app/build/outputs/apk/debug/app-debug.apk'


#test
